force-app/main/default/objects/Product2/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Product</fullName>
            </value>
            <value>
                <fullName>Mast Product</fullName>
            </value>
            <value>
                <fullName>Freight Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Template__c/Quote_Template__c.object-meta.xml
<CustomObject>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Annexure__c.field-meta.xml
<CustomField>
    <fullName>Annexure__c</fullName>
    <label>Annexure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical Details</fullName>
            </value>
            <value>
                <fullName>Product Benefits</fullName>
            </value>
            <value>
                <fullName>Extended Warranty Plan</fullName>
            </value>
            <value>
                <fullName>Optional Safety Accessories</fullName>
            </value>
            <value>
                <fullName>Price Matrix &amp; Commercial Terms</fullName>
            </value>
            <value>
                <fullName>General Terms and Conditions for Sale of Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/fields/Content_Line_Spacing__c.field-meta.xml
<CustomField>
    <fullName>Content_Line_Spacing__c</fullName>
    <label>Content Line Spacing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Image_Height__c.field-meta.xml
<CustomField>
    <fullName>Image_Height__c</fullName>
    <label>Image Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Image_Width__c.field-meta.xml
<CustomField>
    <fullName>Image_Width__c</fullName>
    <label>Image Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Page_Break__c.field-meta.xml
<CustomField>
    <fullName>Page_Break__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Page Break</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Product_Specification_Row_Spacing__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification_Row_Spacing__c</fullName>
    <label>Product Specification Row Spacing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/QRCode_Image_Name__c.field-meta.xml
<CustomField>
    <fullName>QRCode_Image_Name__c</fullName>
    <label>QRCode Image Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Quote_Template__c.field-meta.xml
<CustomField>
    <fullName>Quote_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Template</label>
    <referenceTo>Quote_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/QuoteLineItem_Filter__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItem_Filter__c</fullName>
    <label>QuoteLineItem Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Section_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Section_Alignment__c</fullName>
    <label>Section Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>left</fullName>
            </value>
            <value>
                <fullName>center</fullName>
            </value>
            <value>
                <fullName>rignt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/fields/Section_Related_Base_Product__c.field-meta.xml
<CustomField>
    <fullName>Section_Related_Base_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section Related Base Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Show_Header__c.field-meta.xml
<CustomField>
    <fullName>Show_Header__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Sort_By_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Sort_By_Parameter__c</fullName>
    <label>Sort By Parameter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Table_Object__c.field-meta.xml
<CustomField>
    <fullName>Table_Object__c</fullName>
    <label>Table Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dynamic Text</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Image With Text</fullName>
            </value>
            <value>
                <fullName>Image With QRCode</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Product Specification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FilteredSections.cls
public class FilteredSections {

    public static List<Section__c> getsectionRecords(Id quoteTemplateId, Id quoteId, User u){

        return [SELECT
    Id,
    Name,
    Type__c,
    Quote_Template__c,
    Annexure__c,
    Section_Alignment__c,
    Display_Order__c,
    Page_Break__c,
    Show_Header__c,
    Content__c,
    Content_Line_Spacing__c,
    Image_Name__c,
    Image_Width__c,
    Image_Height__c,
    QRCode_Image_Name__c,
    Product_Specification_Row_Spacing__c,
    Sort_By_Parameter__c,
    Table_Object__c,
    QuoteLineItem_Filter__c,
    Section_Related_Base_Product__c,
    Section_Related_Base_Product__r.Component_Type__c
FROM Section__c
WHERE Quote_Template__c = :quoteTemplateId
ORDER BY Display_Order__c ASC
        ];
    }
}